name: Time-Based Cloud Armor Update

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:        # Manual trigger available

env:
  REGION: us-central1

jobs:
  update_armor_policy:
    runs-on: ubuntu-latest
    environment: production  # Set the environment name where the vars are stored

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Init
        run: terraform init

      - name: Get Current UTC Time
        id: get_time
        run: echo "current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT

      - name: Terraform Apply (time-controlled)
        run: |
          terraform apply -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT }}" \
            -var="region=${{ env.REGION }}" \
            -var="start_time=${{ vars.START_TIME }}" \
            -var="end_time=${{ vars.END_TIME }}" \
            -var="current_time=${{ steps.get_time.outputs.current_time }}"